//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactInfo.DBEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionId { get; set; }
        public string MedicineName { get; set; }
        public int PatientId { get; set; }
        public Nullable<bool> Morning { get; set; }
        public Nullable<bool> Afternoon { get; set; }
        public Nullable<bool> Night { get; set; }
        public Nullable<bool> BeforeEat { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual PatientDetail PatientDetail { get; set; }
    }
}
